require('dotenv').config();
const mongoose = require('mongoose');
const User = require('./models/User');
const bcrypt = require('bcryptjs');
const Boat = require('./models/Boat');
const Event = require('./models/Event');
const Announcement = require('./models/Announcement');

const MONGO_URI = process.env.MONGO_URI;

async function getUsers() {
  const hashedAdmin = await bcrypt.hash('admin', 10);
  return [
    {
      nombre: 'Admin',
      apellido: 'Admin',
      email: 'admin@admin.com',
      rol: 'admin',
      password: hashedAdmin,
    },
    {
      nombre: 'Sebastian',
      apellido: 'Muñoz',
      email: 'smunoz.id@gmail.com',
      rol: 'admin',
      password: await bcrypt.hash('123456', 10),
    },
    {
      nombre: 'Emilio',
      apellido: 'Desantis',
      email: 'emilio@example.com',
      rol: 'entrenador',
      password: await bcrypt.hash('123456', 10),
    },
    {
      nombre: 'Pamela',
      apellido: 'Borgetto',
      email: 'pborgetto@gmail.com',
      rol: 'mantenimiento',
      password: await bcrypt.hash('123456', 10),
    },
  ];
}

async function seed() {
  try {
    await mongoose.connect(MONGO_URI);
    console.log('Conectado a MongoDB');
    await User.deleteMany({});
    const users = await getUsers();
    await User.insertMany(users);
    console.log('Usuarios insertados correctamente');
    // insertar estudiantes
    const Student = require('./models/Student');
    await Student.deleteMany({});
    const mockStudents = [
      {
        Socio_N: "25698",
        nombre: "ALBERTO",
        apellido: "ALONSO",
        Tipo: "Activo",
        Categoria: "Adulto - Master",
        Domicilio: "Mitre 224",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1960-01-18 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "13587982",
        Celular: "3364196902",
        Mail: "albertosn_82@hotmail.com",
        Beca: "NO",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "85779",
        nombre: "MIRIAM",
        apellido: "ALVAREZ",
        Tipo: "Deportivo Mayor",
        Categoria: "Adulto - Master",
        Domicilio: "Urunday 1470",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1959-02-06 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "13588831",
        Celular: "3416108823",
        Mail: "miriamsalvarez59@gmail.com",
        Beca: "",
        Competitivo: "NO",
        Federado: "",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "41778",
        nombre: "ANALI",
        apellido: "BIAGINI",
        Tipo: "Activo",
        Categoria: "Adulto - Master",
        Domicilio: "América 133",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1985-05-23 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "31602183",
        Celular: "3364310213",
        Mail: "analibiagini@gmail.com",
        Beca: "NO",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "85413",
        nombre: "FLAVIA ALEJAN",
        apellido: "BIANCHI",
        Tipo: "Deportivo Mayor",
        Categoria: "Adulto - Master",
        Domicilio: "Av. Moreno 295",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1965-06-12 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "17399982",
        Celular: "3364324995",
        Mail: "flaviabianchi1206@gmail.com",
        Beca: "NO",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "42998",
        nombre: "ELIANA",
        apellido: "BORASI",
        Tipo: "Activo",
        Categoria: "Adulto - Master",
        Domicilio: "Italia 68",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1990-01-25 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "35070347",
        Celular: "3364299379",
        Mail: "eliborasi@gmail.com",
        Beca: "",
        Competitivo: "NO",
        Federado: "",
        Estado: "INACTIVO",
      },
      {
        Socio_N: "43362",
        nombre: "PAMELA DA",
        apellido: "BORGETTO",
        Tipo: "Activo",
        Categoria: "Adulto - Master",
        Domicilio: "Nación 1684",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1989-03-17 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "33109488",
        Celular: "3364256283",
        Mail: "pborgetto@yahoo.com",
        Beca: "NO",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "13677",
        nombre: "MARIANA MAG",
        apellido: "BOTTERI",
        Tipo: "Vitalicio A",
        Categoria: "Adulto - Master",
        Domicilio: "Aguiar 51",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1959-10-25 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "13100689",
        Celular: "",
        Mail: "",
        Beca: "NO",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "27941",
        nombre: "PAOLA VIRGINIA",
        apellido: "CARA",
        Tipo: "Activo",
        Categoria: "Adulto - Master",
        Domicilio: "Rivadavia 176",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1975-08-07 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "24714570",
        Celular: "3364361041",
        Mail: "carapaolavirginia@gmail.com",
        Beca: "NO",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "85821",
        nombre: "GUILLERMO",
        apellido: "CARIGNANI",
        Tipo: "Deportivo Mayor",
        Categoria: "Adulto - Master",
        Domicilio: "Alem 330",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1970-06-15 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "21525418",
        Celular: "3364617754",
        Mail: "guillermo.carignani@gmail.com",
        Beca: "",
        Competitivo: "NO",
        Federado: "",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "18714",
        nombre: "MARIA IRENE",
        apellido: "CARTEY",
        Tipo: "Pre Vitalicio",
        Categoria: "Adulto - Master",
        Domicilio: "Aguiar 33 P.4 D.I",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1968-09-10 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "20459763",
        Celular: "",
        Mail: "irenecartey@hotmail.com.ar",
        Beca: "NO",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "15948",
        nombre: "CRISTINA",
        apellido: "CASTELLI",
        Tipo: "Vitalicio A",
        Categoria: "Adulto - Master",
        Domicilio: "Alvear 431",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1963-12-26 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "16595380",
        Celular: "3364670594",
        Mail: "cristinacastellig@gmail.com",
        Beca: "",
        Competitivo: "NO",
        Federado: "",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "85824",
        nombre: "NICOLAS",
        apellido: "CHURICHI",
        Tipo: "Deportivo Mayor",
        Categoria: "Adulto - Master",
        Domicilio: "Chaco 255",
        Ciudad: "Empalme",
        Fecha_Nac: "1989-06-05 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "34527125",
        Celular: "3412119312",
        Mail: "nicolaschurichi@hotmail.com",
        Beca: "",
        Competitivo: "NO",
        Federado: "",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "28133",
        nombre: "MARIA ELIZABETH",
        apellido: "CIMINARI",
        Tipo: "Activo",
        Categoria: "Adulto - Master",
        Domicilio: "Cernadas 317",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1973-08-20 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "23476392",
        Celular: "3364605168",
        Mail: "eciminari@yahoo.com.ar",
        Beca: "",
        Competitivo: "NO",
        Federado: "",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "80627",
        nombre: "FAUSTO EST",
        apellido: "CLAVERINI",
        Tipo: "Deportivo B",
        Categoria: "Adulto - Master",
        Domicilio: "Viamonte 788",
        Ciudad: "San Nicolas",
        Fecha_Nac: "2001-09-19 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "43590485",
        Celular: "",
        Mail: "",
        Beca: "SI",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "85201",
        nombre: "FAUSTO DANIEL",
        apellido: "COLAZO",
        Tipo: "Deportivo Mayor",
        Categoria: "Adulto - Master",
        Domicilio: "Chacabuco 195",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1997-12-22 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "40858737",
        Celular: "3364366134",
        Mail: "faustocolazo.18@gmail.com",
        Beca: "NO",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "31069",
        nombre: "CONSTANZA",
        apellido: "COMPÁ",
        Tipo: "Activo",
        Categoria: "Adulto - Master",
        Domicilio: "25 de Mayo 138",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1979-11-20 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "27862402",
        Celular: "3364211866",
        Mail: "coticompa@hotmail.com",
        Beca: "",
        Competitivo: "NO",
        Federado: "",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "17990",
        nombre: "SILVIA CR",
        apellido: "COTTARELLI",
        Tipo: "Activo",
        Categoria: "Adulto - Master",
        Domicilio: "Juan B. Justo 0262",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1960-09-28 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "14115475",
        Celular: "3364314007",
        Mail: "silviacottarelli@gmail.com",
        Beca: "NO",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "20601",
        nombre: "GUILLERMINA",
        apellido: "CRIGNA",
        Tipo: "Pre Vitalicio",
        Categoria: "Adulto - Master",
        Domicilio: "Alvear 1036",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1970-11-14 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "21890240",
        Celular: "3364657946",
        Mail: "guillerminacrigna@hotmail.com",
        Beca: "NO",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "31494",
        nombre: "SILVINA ANDREA",
        apellido: "DE PAULI",
        Tipo: "Activo",
        Categoria: "Adulto - Master",
        Domicilio: "San Lorenzo 510",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1976-05-14 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "25262640",
        Celular: "3364598831",
        Mail: "sildepauli13@gmail.com",
        Beca: "NO",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "44463",
        nombre: "LEILA",
        apellido: "DONZELLA",
        Tipo: "Activo",
        Categoria: "Adulto - Master",
        Domicilio: "Alem 348",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1989-09-29 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "34452417",
        Celular: "3364516072",
        Mail: "donzellaleila@gmail.com",
        Beca: "NO",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "85337",
        nombre: "GERMAN ALEJA",
        apellido: "DRUSIN",
        Tipo: "Deportivo B",
        Categoria: "Adulto - Master",
        Domicilio: "12 de Octubre 448",
        Ciudad: "Villa Constitucion",
        Fecha_Nac: "2004-10-15 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "46043861",
        Celular: "",
        Mail: "",
        Beca: "SI",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "44497",
        nombre: "PATRICIA BEATRIZ",
        apellido: "FERNANDEZ",
        Tipo: "Activo",
        Categoria: "Adulto - Master",
        Domicilio: "Soler 222",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1959-01-04 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "13449369",
        Celular: "3364607348",
        Mail: "patriciabfernandez@hotmail.com",
        Beca: "",
        Competitivo: "NO",
        Federado: "",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "40362",
        nombre: "PERLO AGUSTIN",
        apellido: "FERNANDEZ PERLO",
        Tipo: "Activo",
        Categoria: "Adulto - Master",
        Domicilio: "Av. Savio 367",
        Ciudad: "San Nicolas",
        Fecha_Nac: "2001-03-14 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "42593782",
        Celular: "",
        Mail: "",
        Beca: "",
        Competitivo: "NO",
        Federado: "",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "81468",
        nombre: "WALTER DANIEL",
        apellido: "FERNANDEZ",
        Tipo: "Deportivo B",
        Categoria: "Adulto - Master",
        Domicilio: "Almafuerte 985",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1961-03-10 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "14373085",
        Celular: "3364518693",
        Mail: "walterdanielfernandez1961@gmail.com",
        Beca: "SI",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "85358",
        nombre: "SILVIA",
        apellido: "FORTUNA",
        Tipo: "Deportivo Mayor",
        Categoria: "Adulto - Master",
        Domicilio: "Av. Falcón 634",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1970-01-04 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "21488247",
        Celular: "3364210454",
        Mail: "silfortuna70@gmail.com",
        Beca: "NO",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "15584",
        nombre: "MAGDELENA",
        apellido: "GALLO",
        Tipo: "Activo",
        Categoria: "Adulto - Master",
        Domicilio: "Nación 187",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1963-04-02 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "16595140",
        Celular: "3364311959",
        Mail: "coqui.gallo@live.com.ar",
        Beca: "NO",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "85561",
        nombre: "ANALIA INES",
        apellido: "GENTA",
        Tipo: "Deportivo Mayor",
        Categoria: "Adulto - Master",
        Domicilio: "Pellegrini 0715",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1966-06-21 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "18149696",
        Celular: "3364657356",
        Mail: "analiaines66@hotmail.com",
        Beca: "NO",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "15886",
        nombre: "PATRICIA MART",
        apellido: "GOMEZ",
        Tipo: "Familiar",
        Categoria: "Adulto - Master",
        Domicilio: "Don Bosco 814",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1964-01-06 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "16695265",
        Celular: "3364404904",
        Mail: "patricia.marta.gomez@gmail.com",
        Beca: "NO",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "42689",
        nombre: "GASTON",
        apellido: "GONZALEZ",
        Tipo: "Activo",
        Categoria: "Adulto - Master",
        Domicilio: "Soler 0149",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1986-04-20 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "32379229",
        Celular: "3364346549",
        Mail: "cpngastongonzalez@gmail.com",
        Beca: "NO",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "85331",
        nombre: "DORA GRACIELA",
        apellido: "GUTIERREZ",
        Tipo: "Deportivo Mayor",
        Categoria: "Adulto - Master",
        Domicilio: "Obligado 199",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1961-11-06 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "14545701",
        Celular: "",
        Mail: "",
        Beca: "",
        Competitivo: "NO",
        Federado: "",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "24991",
        nombre: "MARIA LORENA",
        apellido: "HUERGO",
        Tipo: "Activo",
        Categoria: "Adulto - Master",
        Domicilio: "Sarmiento 68 P7 D6",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1975-07-07 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "24714172",
        Celular: "3364564140",
        Mail: "mlorenahuergo@hotmail.com",
        Beca: "",
        Competitivo: "NO",
        Federado: "",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "15439",
        nombre: "CECILIA GRAC",
        apellido: "LAFALCE",
        Tipo: "Familiar",
        Categoria: "Adulto - Master",
        Domicilio: "Mitre 224 1 B",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1962-09-30 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "16049645",
        Celular: "3364334028",
        Mail: "cecilia_laf@hotmail.com",
        Beca: "NO",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "17020",
        nombre: "ANA DANIELA",
        apellido: "LITA",
        Tipo: "Activo",
        Categoria: "Adulto - Master",
        Domicilio: "Av. Falcon 152 1°B",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1966-11-30 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "18616384",
        Celular: "3364532854",
        Mail: "anadlita@hotmail.com",
        Beca: "NO",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "44328",
        nombre: "AUGUSTO",
        apellido: "LORENZO",
        Tipo: "Activo",
        Categoria: "Adulto - Master",
        Domicilio: "Avellaneda 16",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1990-09-12 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "35139565",
        Celular: "",
        Mail: "",
        Beca: "",
        Competitivo: "NO",
        Federado: "",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "44328",
        nombre: "LEANDRO",
        apellido: "MALAPLAT",
        Tipo: "Activo",
        Categoria: "Adulto - Master",
        Domicilio: "Cernadas 185",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1989-01-02 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "34044865",
        Celular: "336442184",
        Mail: "leomalaplat18@gmail.com",
        Beca: "NO",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "20345",
        nombre: "MART",
        apellido: "MARIEZCURRENA",
        Tipo: "Activo",
        Categoria: "Adulto - Master",
        Domicilio: "España 0065",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1967-01-01 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "18149700",
        Celular: "",
        Mail: "martinmariezcurrena@yahoo",
        Beca: "NO",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "84741",
        nombre: "AGUSTIN",
        apellido: "MARTOGLIO",
        Tipo: "Deportivo Mayor",
        Categoria: "Adulto - Master",
        Domicilio: "San José 206",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1990-02-24 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "35404317",
        Celular: "3364201531",
        Mail: "martoglioagustin@gmail.com",
        Beca: "",
        Competitivo: "NO",
        Federado: "",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "41565",
        nombre: "MARCEL",
        apellido: "MASTROIANNI",
        Tipo: "Activo",
        Categoria: "Adulto - Master",
        Domicilio: "Maipú 281",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1967-12-11 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "18440355",
        Celular: "",
        Mail: "marcelo.mastroianni1@gmail.com",
        Beca: "NO",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "41561",
        nombre: "RAUL ALBERTO",
        apellido: "MORENO",
        Tipo: "Activo",
        Categoria: "Adulto - Master",
        Domicilio: "San Lorenzo 510",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1970-08-13 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "21525774",
        Celular: "3364601214",
        Mail: "raul.moreno@arcelormittal.com.ar",
        Beca: "NO",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "85633",
        nombre: "LUIS ALBERTO",
        apellido: "MUNOZ",
        Tipo: "Deportivo Mayor",
        Categoria: "Adulto - Master",
        Domicilio: "Damaso Valdes 597",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1958-09-28 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "12519962",
        Celular: "3364513512",
        Mail: "luisalbertomz@gmail.com",
        Beca: "NO",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "35851",
        nombre: "SEBASTIAN",
        apellido: "MUNOZ",
        Tipo: "Activo",
        Categoria: "Adulto - Master",
        Domicilio: "Rioja 66",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1990-01-15 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "35070283",
        Celular: "3364205059",
        Mail: "smunoz.id@gmail.com",
        Beca: "NO",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "37511",
        nombre: "MORA",
        apellido: "NARDONE",
        Tipo: "Activo",
        Categoria: "Adulto - Master",
        Domicilio: "Italia 523",
        Ciudad: "San Nicolas",
        Fecha_Nac: "2000-06-30 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "42569835",
        Celular: "3364374844",
        Mail: "moranardone2@gmail.com",
        Beca: "",
        Competitivo: "NO",
        Federado: "",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "22717",
        nombre: "STELLA MARIS",
        apellido: "NASIF",
        Tipo: "Activo",
        Categoria: "Adulto - Master",
        Domicilio: "J. Ingenieros 0176",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1960-10-24 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "14115381",
        Celular: "3364626162",
        Mail: "Stellamna241060@gmail.com",
        Beca: "NO",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "44565",
        nombre: "ROMAN",
        apellido: "PANIZZOLI",
        Tipo: "Activo",
        Categoria: "Adulto - Master",
        Domicilio: "San José 316",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1983-04-17 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "30026466",
        Celular: "3364699650",
        Mail: "romanpanizzoli@gmail.com",
        Beca: "",
        Competitivo: "NO",
        Federado: "",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "21522",
        nombre: "LILIANA GABRIELA",
        apellido: "PETROCELLI",
        Tipo: "Vitalicio A",
        Categoria: "Adulto - Master",
        Domicilio: "Chacabuco 179",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1961-01-11 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "14373121",
        Celular: "3364682948",
        Mail: "glpetrocelli@hotmail.com",
        Beca: "NO",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "14676",
        nombre: "GUSTAVO MARCELO",
        apellido: "PETRUCCI",
        Tipo: "Activo",
        Categoria: "Adulto - Master",
        Domicilio: "AMERICA 0118",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1962-05-07 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "14545845",
        Celular: "3364247055",
        Mail: "marcci1928@gmail.com",
        Beca: "NO",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "18538",
        nombre: "NANCY DELIA",
        apellido: "PICABEA",
        Tipo: "Activo",
        Categoria: "Adulto - Master",
        Domicilio: "Av Savio 540",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1961-11-06 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "14545636",
        Celular: "3364336111",
        Mail: "nancypicabea@gmail.com",
        Beca: "",
        Competitivo: "NO",
        Federado: "",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "33355",
        nombre: "RENATA ANTONELA",
        apellido: "PINI",
        Tipo: "Activo",
        Categoria: "Adulto - Master",
        Domicilio: "Leon Guruciaga 223",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1985-10-01 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "31909094",
        Celular: "",
        Mail: "",
        Beca: "",
        Competitivo: "NO",
        Federado: "",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "85818",
        nombre: "FEDERICO",
        apellido: "QUINTANA",
        Tipo: "Deportivo Mayor",
        Categoria: "Adulto - Master",
        Domicilio: "Peatonal 4 531",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1971-03-30 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "22039967",
        Celular: "",
        Mail: "",
        Beca: "",
        Competitivo: "NO",
        Federado: "",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "42607",
        nombre: "ANAHI",
        apellido: "QUIQUISOLA",
        Tipo: "Activo",
        Categoria: "Adulto - Master",
        Domicilio: "Victorica 645",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1985-02-04 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "31151742",
        Celular: "3364374018",
        Mail: "anahiquiquisola@gmail.com",
        Beca: "NO",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "25404",
        nombre: "ROSANA",
        apellido: "RAITERI",
        Tipo: "Pre Vitalicio",
        Categoria: "Adulto - Master",
        Domicilio: "Necochea 223",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1969-02-22 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "20642535",
        Celular: "33644615673",
        Mail: "olivera884@hotmail.com",
        Beca: "",
        Competitivo: "NO",
        Federado: "",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "43038",
        nombre: "CECILIA",
        apellido: "RIVA",
        Tipo: "Activo",
        Categoria: "Adulto - Master",
        Domicilio: "Catagnino 644",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1960-11-17 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "14115684",
        Celular: "3364011021",
        Mail: "ceciliariva6000@hotmail.com",
        Beca: "NO",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "19736",
        nombre: "PABLO F",
        apellido: "STOCCAFISSO",
        Tipo: "Activo",
        Categoria: "Adulto - Master",
        Domicilio: "Lavalle 131",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1968-01-18 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "20017600",
        Celular: "3364573135",
        Mail: "pablostocca@hotmail.com",
        Beca: "NO",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "33457",
        nombre: "JULIAN",
        apellido: "TEISSEIRE",
        Tipo: "Activo",
        Categoria: "Adulto - Master",
        Domicilio: "",
        Ciudad: "",
        Fecha_Nac: "",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "",
        Celular: "",
        Mail: "",
        Beca: "",
        Competitivo: "NO",
        Federado: "",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "14453",
        nombre: "HUGO",
        apellido: "TORRES",
        Tipo: "Vitalicio A",
        Categoria: "Adulto - Master",
        Domicilio: "AV. Savio 540",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1962-02-01 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "14545456",
        Celular: "",
        Mail: "",
        Beca: "",
        Competitivo: "NO",
        Federado: "",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "18740",
        nombre: "GRACIELA E",
        apellido: "TRAVERSO",
        Tipo: "Activo",
        Categoria: "Adulto - Master",
        Domicilio: "Las Heras 128",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1959-11-13 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "13587861",
        Celular: "3364663810",
        Mail: "kan5959@hotmail.com",
        Beca: "NO",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "85514",
        nombre: "MARIA LUJAN",
        apellido: "TROTTA",
        Tipo: "Deportivo Mayor",
        Categoria: "Adulto - Master",
        Domicilio: "Nación 0525",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1985-06-04 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "31718045",
        Celular: "3364023322",
        Mail: "lujanfuglini@gmail.com",
        Beca: "NO",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "43364",
        nombre: "GERMAN ANDRES",
        apellido: "VELOZ",
        Tipo: "Activo",
        Categoria: "Adulto - Master",
        Domicilio: "Nación 1684",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1982-08-17 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "29559662",
        Celular: "3364612751",
        Mail: "germanveloz158@gmail.com",
        Beca: "NO",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "25017",
        nombre: "FACUNDO MA",
        apellido: "VIGNOLES",
        Tipo: "Pre Vitalicio",
        Categoria: "Adulto - Master",
        Domicilio: "Brown 229",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1975-12-10 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "24714974",
        Celular: "3364290623",
        Mail: "fvignoles@gmail.com",
        Beca: "NO",
        Competitivo: "NO",
        Federado: "NO",
        Estado: "ACTIVO",
      },
      {
        Socio_N: "85711",
        nombre: "FERNANDO",
        apellido: "VILLEGAS",
        Tipo: "Deportivo Mayor",
        Categoria: "Adulto - Master",
        Domicilio: "Liniers 1443",
        Ciudad: "San Nicolas",
        Fecha_Nac: "1975-05-23 00:00:00",
        Ingreso: "2026-01-01 00:00:00",
        DNI: "24642140",
        Celular: "3402502099",
        Mail: "fernando.villegas.1975@gmail.com",
        Beca: "",
        Competitivo: "NO",
        Federado: "",
        Estado: "ACTIVO",
      },
    ];
    // Map fields from the provided CSV-like objects to the Student model fields.
    // Filter out entries without a DNI to avoid insert errors (dni is required and unique).
    const studentsToInsert = mockStudents
      .filter(s => s.DNI && s.DNI.toString().trim() !== '')
      .map(s => ({
        socioN: s.Socio_N || '',
        tipo: s.Tipo || '',
        ciudad: s.Ciudad || '',
        nombre: s.nombre || '',
        apellido: s.apellido || '',
        dni: s.DNI || '',
        categoria: s.Categoria || '',
        domicilio: s.Domicilio || '',
        nacimiento: s.Fecha_Nac && s.Fecha_Nac.toString().trim() !== '' ? new Date(s.Fecha_Nac) : undefined,
        celular: s.Celular || '',
        email: s.Mail || '',
        beca: s.Beca && s.Beca.toString().toUpperCase() === 'SI' ? true : false,
        competitivo: s.Competitivo && s.Competitivo.toString().toUpperCase() === 'SI' ? true : false,
        federado: s.Federado && s.Federado.toString().toUpperCase() === 'SI' ? true : false,
        estado: s.Estado || '',
        fechaIngreso: s.Ingreso && s.Ingreso.toString().trim() !== '' ? new Date(s.Ingreso) : undefined,
      }));
    if (studentsToInsert.length > 0) {
      await Student.insertMany(studentsToInsert);
      console.log('Estudiantes insertados correctamente');
    } else {
      console.log('No hay estudiantes válidos para insertar');
    }
    // insertar botes
    await Boat.deleteMany({});
    const mockBoats = [
      { nombre: 'Bote 1', tipo: 'single', estado: 'activo', fechaIngreso: new Date('2025-01-01'), nivelDif: 3, row: 2 },
      { nombre: 'Bote 2', tipo: 'doble', estado: 'mantenimiento', fechaIngreso: new Date('2025-02-01'), nivelDif: 2, row: 4 },
      { nombre: 'Bote 3', tipo: 'cuadruple', estado: 'fuera_servicio', fechaIngreso: new Date('2025-03-01'), nivelDif: 4, row: 8 },

    ];
    await Boat.insertMany(mockBoats);
    console.log('Botes insertados correctamente');
    // insertar eventos
    await Event.deleteMany({});
    const mockEvents = [
      {
        title: 'Regata de Primavera',
        date: new Date('2025-03-21'),
        description: 'Competencia anual de remo para celebrar la llegada de la primavera.',
        image: 'spring-regatta.jpg',
      },
      {
        title: 'Copa de Invierno',
        date: new Date('2025-07-15'),
        description: 'Evento de remo en aguas frías para los más valientes.',
        image: 'winter-cup.jpg',
      },
      {
        title: 'Maratón de Remo',
        date: new Date('2025-10-10'),
        description: 'Una maratón de remo para poner a prueba la resistencia.',
        image: 'rowing-marathon.jpg',
      },
    ];
    await Event.insertMany(mockEvents);
    console.log('Eventos de remo agregados exitosamente.');

    // insertar anuncios
    await Announcement.deleteMany({});
    const mockAnnouncements = [
      {
        title: 'Cierre por mantenimiento',
        date: new Date('2025-01-20'),
        description: 'El club permanecerá cerrado por tareas de mantenimiento general.'
      },
      {
        title: 'Nueva indumentaria disponible',
        date: new Date('2025-02-05'),
        description: 'Ya está disponible la nueva ropa oficial del club en la secretaría.'
      },
      {
        title: 'Reunión de subcomisión',
        date: new Date('2025-03-10'),
        description: 'Convocatoria a reunión mensual de la subcomisión de remo.'
      },
      {
        title: 'Clases para principiantes',
        date: new Date('2025-04-01'),
        description: 'Se abren cupos para el curso inicial de remo nivel 1.'
      }
    ];
    await Announcement.insertMany(mockAnnouncements);
    console.log('Anuncios insertados correctamente');
  } catch (err) {
    console.error('Error al insertar usuarios:', err);
  } finally {
    await mongoose.disconnect();
    console.log('Desconectado de MongoDB');
  }
}

seed();
